apiVersion: v1
kind: Service
metadata:
  name: envoy-redis-proxy-clusterip
  labels:
    app: envoy-redis-proxy
spec:
  type: ClusterIP
  ports:
  - name: envoy-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: redis
    port: 6479
    targetPort: 6479
    protocol: TCP
  selector:
    app: envoy-redis-proxy
